#!/bin/bash
# Hydrate application config from AWS SSM Parameter Store
# Usage: ./scripts/hydrate-config.sh <env>
# Example: ./scripts/hydrate-config.sh dev

set -e

ENV=${1:-dev}

echo "Fetching config from SSM for environment: $ENV"

# Fetch auth parameters
USER_POOL_ID=$(aws ssm get-parameter --name "/alphalens/$ENV/auth/userPoolId" --query "Parameter.Value" --output text 2>/dev/null || echo "")
CLIENT_ID=$(aws ssm get-parameter --name "/alphalens/$ENV/auth/clientId" --query "Parameter.Value" --output text 2>/dev/null || echo "")
DOMAIN=$(aws ssm get-parameter --name "/alphalens/$ENV/auth/domain" --query "Parameter.Value" --output text 2>/dev/null || echo "")
REGION=$(aws ssm get-parameter --name "/alphalens/$ENV/auth/region" --query "Parameter.Value" --output text 2>/dev/null || echo "us-east-2")

if [ -z "$USER_POOL_ID" ]; then
    echo "Warning: Could not fetch SSM parameters. Infrastructure may not be deployed."
    echo "Run: make infra-deploy ENV=$ENV FEATURE=F1-1"
    exit 1
fi

echo "Found config:"
echo "  User Pool ID: $USER_POOL_ID"
echo "  Client ID: $CLIENT_ID"
echo "  Domain: $DOMAIN"
echo "  Region: $REGION"

# Update backend .env
cat > backend/.env << EOF
# Backend Environment Variables
# Auto-generated by hydrate-config.sh from SSM parameters
ENV=$ENV

# Auth mode
AUTH_MODE=cognito

# AWS Region
AWS_REGION=$REGION

# Amazon Cognito Configuration
COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
COGNITO_DOMAIN=$DOMAIN

# CORS Origins
CORS_ORIGINS=["http://localhost:3000","http://localhost:3001"]
EOF

echo "Updated backend/.env"

# Update frontend .env.local
cat > frontend/.env.local << EOF
# Frontend Environment Variables
# Auto-generated by hydrate-config.sh from SSM parameters
NEXT_PUBLIC_BACKEND_URL=http://localhost:8000

# AWS Region
NEXT_PUBLIC_AWS_REGION=$REGION

# Amazon Cognito Configuration
NEXT_PUBLIC_COGNITO_USER_POOL_ID=$USER_POOL_ID
NEXT_PUBLIC_COGNITO_CLIENT_ID=$CLIENT_ID
NEXT_PUBLIC_COGNITO_DOMAIN=$DOMAIN
EOF

echo "Updated frontend/.env.local"

# Update config/auth.yaml
cat > config/auth.yaml << EOF
# F1-1 AUTH CONFIGURATION
# Auto-generated by hydrate-config.sh from SSM parameters

aws:
  region: "$REGION"

cognito:
  user_pool_id: "$USER_POOL_ID"
  client_id: "$CLIENT_ID"
  domain: "$DOMAIN"

google_oauth:
  enabled: false

deployment:
  local_frontend_url: "http://localhost:3000"
  local_backend_url: "http://localhost:8000"
  prod_frontend_url: ""
  prod_backend_url: ""
EOF

echo "Updated config/auth.yaml"

echo ""
echo "Config hydration complete!"
